from dotenv import load_dotenv
import os
load_dotenv()

RABBIT_MQ_HOST = os.getenv("RABBIT_MQ_HOST")
RABBIT_MQ_PORT = int(os.getenv("RABBIT_MQ_PORT"))
RABBIT_MQ_SERVER = os.getenv("RABBIT_MQ_SERVER")


EGGPLANT_SUBMIT_TRAINING_QUEUE = os.getenv("EGGPLANT_SUBMIT_TRAINING_QUEUE")
EGGPLANT_SUBMIT_TRAINING_EXCHANGE = os.getenv("EGGPLANT_SUBMIT_TRAINING_EXCHANGE")
EGGPLANT_SUBMIT_PREDICTION_QUEUE = os.getenv("EGGPLANT_SUBMIT_PREDICTION_QUEUE")
EGGPLANT_SUBMIT_PREDICTION_EXCHANGE = os.getenv("EGGPLANT_SUBMIT_PREDICTION_EXCHANGE")
PREDICTION_QUEUE = os.getenv("PREDICTION_QUEUE")
PREDICTION_EXCHANGE = os.getenv("PREDICTION_EXCHANGE")

PREDICTION_ROUTING_KEY = os.getenv("PREDICTION_ROUTING_KEY")
TRAIN_ROUTING_KEY = os.getenv("TRAIN_ROUTING_KEY")
